### ISSUE TITLE
Excel scripting (COM) interface

### ISSUE THREAD

**Issue by wck01** [sdllc/Basic-Excel-R-Toolkit#5]
Hi Duncan,

This is very great for new version 0.55 comes with COM interface. I tried below commands are success:

EXCEL$Application$get_ActiveSheet()$get_UsedRange()$get_Rows()$get_Count()
EXCEL$Application$get_ActiveWorkbook()$get_Path()

However, when I tried some more complicated command which returns error. I'm not sure what's going wrong. Is it too complicated for BERT? I'm just interested what level I can use BERT to automate Excel task. BERT is very useful. I'm very appreciated you develop such tool.

EXCEL$Application$get_ThisWorkbook()
=> Error in EXCEL$Application$get_ThisWorkbook() : 
     COM Exception in Invoke (ThisWorkbook) 0x80020009: Exception occurred.

EXCEL$Application$get_Range("A1")$get_offset(0,1)$get_Value()
=> Error: attempt to apply non-function

**Comment by duncanwerner** [comment]
There are definitely some bugs in there.  In fact there's a known UTF-8 bug in this build, so if you have high-bit characters it won't work properly; that's fixed, I just need to upload a new release.

The best way to figure out the interface is to assign the output of each function to an object (at least while you are developing).  Then you can `ls` the object, or see the tooltips.  So for example, try

```
rng <- Excel$Application$get_Range("A1")
ls( rng )
```

I don't know what `ThisWorkbook` does; but for me, it has the same error in VBA.  If you want the current workbook, try `EXCEL$Application$get_ActiveWorkbook()`.

I think the problem with your second function is it should be `get_Offset` (big O).  But I don't think that `get_Offset` does what you want -- because when I try it, I get

```
> EXCEL$Application$get_Range("A1")$get_Offset( 1, 1 )$get_Address 
"$A$1"
```

You could do something like 

```
> EXCEL$Application$get_Cells()$get_Item(3, 4)$get_Address 
```

See http://bert-toolkit.com/excel-scripting-interface-in-r for an explanation of this syntax.

**Comment by wck01** [comment]
Well. This is more complicated than I expected but this is very useful.

The "ls" command you suggested is very useful for my exploration. For example, I know how to select the second worksheet as below:

EXCEL$Application$get_Worksheets()$get_Item(2)$Select()

Thanks.

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
