### ISSUE TITLE
Microsoft Excel has stopped working

### ISSUE THREAD

**Issue by dustindall** [sdllc/Basic-Excel-R-Toolkit#6]
When I have the BERT add-in enabled and I close out of Excel I get the following message. The issue goes away when I deactivate the add-in. Any idea on what is causing this?

![image](https://cloud.githubusercontent.com/assets/8218382/11701429/20711e62-9e95-11e5-8899-fb55163e4400.png)

**Comment by duncanwerner** [comment]
I don't know what that is, unfortunately it's not a very helpful message.  If Excel is crashing rather than trapping this error, I would guess that it's an access violation (segfault), which means probably a null pointer.  Sloppy.

Does this happen at startup?  Did it ever work, or did it always crash?  And what version of Excel are you using?  The more you can tell me the more likely I can sort it out.

**Comment by dustindall** [comment]
I was able to replicate the work on the quick start guide so everything appears to be working fine. The message pops ups when I close out of Excel and it does it when ever the add-in is enabled. I tried uninstalling and reinstalling BERT but that didn't fix the problem.

I'm running Excel 2013. I installed BERT on another computer using Excel 2016 and I do not get the message.

**Comment by duncanwerner** [comment]
Thanks, that is completely different than what I expected.  It gives me a place to look, though.  I'll check it out and see what I can find.

**Comment by duncanwerner** [comment]
I can't figure out what it might be, it's not anything obvious.  If you are interested, I can put together an instrumented build (one that logs function calls) to try and diagnose it on your machine.

**Comment by dustindall** [comment]
That's alright i have it on one machine which will be enough to get me started.

**Comment by duncanwerner** [comment]
Closing stale threads / non-issues.  If this is an issue and is not resolved, please re-open.
