### ISSUE TITLE
How can I "press" BERT Console button in automated instance of Excel?

### ISSUE THREAD

**Issue by wscheel** [sdllc/Basic-Excel-R-Toolkit#68]
I have an Excel "client" that must run async.  All VBA code is run this way using Application.OnTime.  Real-time data is being streamed in and process by class event handlers.  Like other BERT users who have posted issues involving long R runtimes, I too have that.  So, as a workaround, I create a "server" instance of Excel, and using VBA extensibility I copy a code module into it.  The module's sub's are executed from the client using <server application>.Run.   A BERT.Call appears in a server proc...it has client range information that was passed, and the automated server can do callbacks to client procs.

All this works fine, provided the server instance is "touched."  Touching it appears to be as easy as clicking on the server workbook's icon.  I don't even have to click on the Add-in BERT Console button in the server.  Of course, I neither want the server to be visible nor have to physically touch it.

Can you please tell me how to programmatically "click" on the server's Bert Console icon or otherwise pull this off?

Thanks

**Comment by duncanwerner** [comment]
So first of all, there's no way to open the console programatically, although that's fairly simple to do so we will add it in the next build.  

But I'm not clear on why you want to do that, it seems like it would not have any use in the situation you describe. Do you want to click it or not?

> I don't even have to click on the Add-in BERT Console button in the server

It might be useful for debugging, but BERT is going to run whether or not you open the console.  

That notwithstanding, it would be better to run R in the background (via `parallel` or something similar) than to run Excel in the background, because even in the background Excel has an event loop. I recognize that this is complicated, particularly if you're coming from an Excel background rather than an R background.  Maybe we can write up a guide at some point.

**Comment by wscheel** [comment]
What I meant was an automated Excel does not have a running BERT connection unless one makes it visible and then touches it, say by opening the automated excel server version (which has now been populated with VBA code).

The testing of the server VBA code occurs by putting a breakpoint in the client just before it Runs a server sub containing Application.Run("BERT.Call",...) but after it has populated the server Excel with a VBA module via extensibility code.  You then can switch over to the server while debugging the client debug to see what's going on when a Run call is made by the client to the server.  Under those conditions, the client-server works fine and BERT.Call is successfull.  However, if the client is NOT breaked but just allowed to run without the server being "touched", the server's BERT.Call fails.

Anyway, a synchronous call either through a cell macro =R.<function> ala a Calculate or by a direct call to BERT.Call in the client workbook won't work.  The reason is that It ties up the client that is doing other things (asynchronously).  I don't know about R parallel, but the whole problem appears to be either the cell-based call or sub-based call which is synchronous and hangs out until the R code has completed execution.

So, unless I can accidently stumble on a solution, I need the ability to "press" the BERT Console button from a subroutine.  I can do this for buttons in, say, the workbook menu using Office commandbar controls.  But, can't find the BERT Console button.  Don't know how to programmatically run its Action.

Any ideas?

**Comment by duncanwerner** [comment]
Like I said, we can add a way to programatically push the button.  (And I'll do that shortly).  But that's almost certainly not the problem.  I suspect it has something to do with timing.  Let me see if I can figure it out.

Regarding parallel, R is single-threaded.  Parallel does pretty much what you are doing with Excel, that is, launching a background instance for calculation.  Because that runs out of process, it's async with respect to the original process.

**Comment by wscheel** [comment]
Yes, you are correct.  It is a timing issued.  I put a 2 sec delay in the client after it has automated the server, and it now works fine.

Not really sure there is a real need for being able to press  the BERT Console button.
