### ISSUE TITLE
Increase number of functions slots

### ISSUE THREAD

**Issue by mnar53** [sdllc/Basic-Excel-R-Toolkit#8]
Tried it, works very well and I like it. But I'd increase MAX_FUNCTION_COUNT, 100 is definitevely too small (I made it 2,000, changing accordingly the def file and the thunks in bert.cpp)

**Comment by duncanwerner** [comment]
As you saw it's an arbitrary limit.  Because it requires exporting symbols, there's no practical way to make it dynamic (as far as I know), but it could be increased.  I'm not sure 2K is necessarily the right number, but since you can always recompile the actual value isn't critical.  I'll up it in a future build.

**Comment by duncanwerner** [comment]
Upped to 2048 in release v0.70.
