### ISSUE TITLE
Incomplete array formula support

### ISSUE THREAD

**Issue by StatsMan53** [sdllc/Basic-Excel-R-Toolkit#83]
Place the following 1-line function in the BERT\functions directory
   test <- function() 1:3

In Excel, select A1:A3 and array enter (Ctrl-Shift-Enter) 
   =R.test()
If done correctly, the formula bar will show
   {=R.test}
The untyped curly braces indicate that Excel accepted it as an array formula.  The result is 1 in A1, 2 in A2, and 3 in A3, showing that a single Excel array formula can return multiple values (1 per cell).  Also showing that R vectors, are populated by BERT as vertical arrays in Excel.

If a horizontal array were wanted in Excel, an experienced Excel user would simply select 3 cells in a row (say C1:E1) and array enter
   =TRANSPOSE(R.test())
but instead of 1 in C1, 2 in D1, and 3 in E1, BERT returns 1 in each of C1:E1.

If the same array formula is entered in C3:E4, then BERT returns 1 in C3, 2 in D3, and #N/A in E3:E4

If the same array formula is entered in C6:E8, then BERT finally returns the expected 1 in C6, 2 in D6, and 3 in E6, but at the cost of tying up cells C7:E8 to no purpose other than tricking BERT into doing the right thing.

It looks as though when BERT returns a vector, it shortens that return vector to the number of rows that were selected for the formula, but the BERT function may be wrapped in Excel functions that are intended to operate on values that BERT thinks are unwanted.  Given the way Excel array functions are intended to operate, BERT should give the full return vector regardless of the number of cells selected for the array formula.
![image](https://user-images.githubusercontent.com/33853646/33054726-fe772a5a-ce48-11e7-9c91-c57097415b6e.png)

**Comment by duncanwerner** [comment]
Are you using a current version of BERT? If not, you might want to upgrade.  This sounds like some array padding that we used to do, but do not do anymore (as of a couple of months).  Also I assume this is a typo, but `{R.test}` is never going to work. That will return the function address (a pointer).

**Comment by StatsMan53** [comment]
You are correct.  This issue appears to have fixed subsequent to my original installation nearly 6 months ago.

This is a very useful tool.  Thank you.

**Comment by duncanwerner** [comment]
So the original use cases for BERT (and predecessors) were pretty simple -- getting data into and out of Excel.  At some point we started doing "truncating and padding" to array functions.  The aim was to make the data more presentable; if you had an array larger than the data size, it would show whitespace instead of "#NA" errors.  Similarly if the array was smaller, the result would be truncated.

As long as the R-Excel bridge is the last step in your process, that works OK.  But we heard from more Excel-minded people that functions were not behaving as expected if chained together or part of more complicated formulae.  There's a long discussion in another issue that led me to change the default behavior, I think for the better.

Which is all a long way of saying if something seems incorrect, please let us know, regardless of whether we agree with you, or whether we've already fixed it.
