### ISSUE TITLE
Setting graphics parameters

### ISSUE THREAD

**Issue by FrankAcito** [sdllc/Basic-Excel-R-Toolkit#90]
Is there any way to increase the size of the graphics image returned to Excel? I tried to set the size using par(din=c(10,10)), but this does not work. Is there a parameter in BERT.graphics.devices() that can be set?
Thanks.

**Comment by duncanwerner** [comment]
`width` and `height`, or just resize with the mouse.  See `?BERT.graphics.device`.

**Comment by FrankAcito** [comment]
??Hello,

Thanks for the quick response. I found that I could instead create a pdf file from the R code and size that as needed. The problem is that BERT graphics returns an image of fixed size. It cannot be effectively resized once in Excel. I tried resetting several different parameters for graphics in the BERT R console, but was unable to change the dimensions from about 5.7 by 5.7.


In any case, thanks so much for developing this tool. I will be using it in my classes in the next few months. Also, I wonder if it would be useful to create a place where users could share their examples using BERT. I have developed some VBA to interface with R regression, logistic regression, and naive Bayes. I working on additional tools and would be willing to share these.


Frank Acito

Professor

Kelley School of Business

Indiana University

Bloomington, Indiana

________________________________

**Comment by duncanwerner** [comment]
If you resize the graph in Excel, you need to redraw it.  There's no way for us to get notified of the resize (short of polling, which we won't do). We use raster graphics because there's no support for any vector format in Excel. PDFs will always print better than anything we can draw in Excel for that reason.

Having a place for contributed content is a good idea, we'll set something up.  But this (github issues) is not a good platform for communication, send me an email directly if you would like to disucss.
